#include "ronny.h"
// #include "g/keymap_combo.h"
#ifdef CONSOLE_ENABLE
#    include "print.h"
#endif

// clang-format off
#define LAYOUT_dactyl_wrapper(...) LAYOUT_5x6(__VA_ARGS__)
#define LAYOUT_dactyl_base( \
    K01, K02, K03, K04, K05, K06, K07, K08, K09, K0A, \
    K11, K12, K13, K14, K15, K16, K17, K18, K19, K1A, \
    K21, K22, K23, K24, K25, K26, K27, K28, K29, K2A  \
  ) \
  LAYOUT_dactyl_wrapper( \
    KC_TAB,   ________________NUMBER_LEFT________________,              ________________NUMBER_RIGHT_______________,       KC_DEL,         \
    CTL_ESC,  K01,      K02,      K03,      K04,      K05,              K06,     K07,     K08,     K09,     K0A,   KC_BSPC,        \
    KC_LSFT , K11,      K12,      K13,      K14,      K15,              K16,     K17,     K18,     K19,     K1A,   KC_QUOT,        \
    KC_LCTL,  K21,      K22,      K23,      K24,      K25,              K26,     K27,     K28,     K29,     K2A,   RSFT_T(KC_ENT), \
                        KC_LBRC,KC_RBRC,                                               KC_PLUS, KC_EQL, \
                                            KC_ESC,KC_SPC,              KC_ENT, KC_ESC,              \
                                            KC_TAB,KC_HOME,            KC_END,  KC_DEL,            \
                                            KC_BSPC, KC_GRV,           KC_LGUI, KC_LALT            \
)

#define LAYOUT_dactyl_base_wrapper(...) LAYOUT_dactyl_base(__VA_ARGS__)

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    /*                ┌───────┬───────┬───────┬───────┐ ┌───────┬───────┬───────┬───────┐
    * ┌───────┬───────┤   `   │   "   │  F4   │  F5   │ │   ¨   │   ^   │   È   │   É   ├───────┬──────┐
    * │ UNDO  │ REDO  ├───────┼───────┼───────┼───────┤ ├───────┼───────┼───────┼───────┤  F10  │ F11  │
    * ├───────┼───────┤   W   │   F   │   P   │   B   │ │   J   │   L   │   U   │   Y   ├───────┼──────┤
    * │   À   │   Q   ├───────┼───────┼───────┼───────┤ ├───────┼───────┼───────┼───────┤  : ;  │ - _  │
    * ├───────┼───────┤  R/⎇  │  S/⇧  │  T/⎈  │   G   │ │   M   │  N/⎈  │  E/⇧  │  I/⎇  ├───────┼──────┤
    * │  ESC  │  A/◆  ├───────┼───────┼───────┼───────┤ ├───────┼───────┼───────┼───────┤  O/◆  │ ' "  │
    * ├───────┼───────┤   X   │   C   │   D   │   V   │ │   K   │   H   │  , <  │  . >  ├───────┼──────┤
    * │   Z   │REPEAT ├───────┼───────┼───────┴───────┘ └───────┴───────┼───────┼───────┤  / ?  │-> => │
    * └───────┴───────┤TG_MIC │   Ç   │                                 │ AltGr │   `   ├───────┴──────┘
    *                 └───────┴───────┘                                 └───────┴───────┘
    *                                 ┏━━━━━━━┳━━━━━━━┓ ┏━━━━━━━┳━━━━━━━┓
    *                                 ┃TAB/NAV┃  SPC  ┃ ┃ BSPC  ┃ ⏎/SYM ┃
    *                                 ┡━━━━━━━╋━━━━━━━┫ ┣━━━━━━━╋━━━━━━━┩
    *                                 │COMPOSE┃1-SHOT⇧┃ ┃1-SHOT⇧┃  UP   │
    *                                 ├───────╄━━━━━━━┩ ┡━━━━━━━╃───────┤
    *                                 │PLOVER │CAPS/MS│ │SWAPHND│ DOWN  │
    *                                 └───────┴───────┘ └───────┴───────┘       generated by [keymapviz] */

    [_QWERTY] = LAYOUT_dactyl_base_wrapper(
        _________________QWERTY_L1_________________, _________________QWERTY_R1_________________,
        _________________QWERTY_L2_________________, _________________QWERTY_R2_________________,
        _________________QWERTY_L3_________________, _________________QWERTY_R3_________________
    )
};
// clang-format on
